"""init

Revision ID: 020c6d183ad1
Revises: d5c6c1541f5e
Create Date: 2023-09-10 11:02:56.337833

"""

# revision identifiers, used by Alembic.
revision = '020c6d183ad1'
down_revision = 'd5c6c1541f5e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
