"""init

Revision ID: 0e4fd26b733a
Revises: 1ba3f27cff46
Create Date: 2023-09-11 22:16:49.249213

"""

# revision identifiers, used by Alembic.
revision = '0e4fd26b733a'
down_revision = '1ba3f27cff46'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
