"""init

Revision ID: 1494aa305d9a
Revises: ae8c6a718f04
Create Date: 2023-09-10 09:42:52.395868

"""

# revision identifiers, used by Alembic.
revision = '1494aa305d9a'
down_revision = 'ae8c6a718f04'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
