"""init

Revision ID: 15cacf37e03a
Revises: ddea345a6dba
Create Date: 2023-09-10 09:56:35.552670

"""

# revision identifiers, used by Alembic.
revision = '15cacf37e03a'
down_revision = 'ddea345a6dba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
