"""init

Revision ID: 16192d0c8c5f
Revises: c2212ad9705c
Create Date: 2023-09-11 19:50:24.366355

"""

# revision identifiers, used by Alembic.
revision = '16192d0c8c5f'
down_revision = 'c2212ad9705c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
