"""init

Revision ID: 1693fd838c7d
Revises: 4b977fc9b56b
Create Date: 2023-09-10 09:43:55.292993

"""

# revision identifiers, used by Alembic.
revision = '1693fd838c7d'
down_revision = '4b977fc9b56b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
