"""init

Revision ID: 1733abbfd661
Revises: ad18d73f9a45
Create Date: 2023-09-11 19:18:03.568128

"""

# revision identifiers, used by Alembic.
revision = '1733abbfd661'
down_revision = 'ad18d73f9a45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
