"""init

Revision ID: 1ba3f27cff46
Revises: fd8aaf8f7e94
Create Date: 2023-09-11 19:53:24.085065

"""

# revision identifiers, used by Alembic.
revision = '1ba3f27cff46'
down_revision = 'fd8aaf8f7e94'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
