"""init

Revision ID: 1c79a57c2247
Revises: f23ee48fd220
Create Date: 2023-09-11 22:25:47.987140

"""

# revision identifiers, used by Alembic.
revision = '1c79a57c2247'
down_revision = 'f23ee48fd220'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
