"""init

Revision ID: 25fe01d31c06
Revises: 33e13a4f8b1e
Create Date: 2023-09-10 10:07:47.604106

"""

# revision identifiers, used by Alembic.
revision = '25fe01d31c06'
down_revision = '33e13a4f8b1e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
