"""init

Revision ID: 2c94aa7d77bb
Revises: 0e4fd26b733a
Create Date: 2023-09-11 22:20:06.099370

"""

# revision identifiers, used by Alembic.
revision = '2c94aa7d77bb'
down_revision = '0e4fd26b733a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
