"""init

Revision ID: 33e13a4f8b1e
Revises: fe7779a44444
Create Date: 2023-09-10 10:01:07.867183

"""

# revision identifiers, used by Alembic.
revision = '33e13a4f8b1e'
down_revision = 'fe7779a44444'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
