"""init

Revision ID: 38b6588e6618
Revises: 56242c2e5b2f
Create Date: 2023-09-06 08:57:26.131042

"""

# revision identifiers, used by Alembic.
revision = '38b6588e6618'
down_revision = '56242c2e5b2f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
