"""init

Revision ID: 390c5583f6d7
Revises: b7313ee54cff
Create Date: 2023-09-06 09:44:39.377976

"""

# revision identifiers, used by Alembic.
revision = '390c5583f6d7'
down_revision = 'b7313ee54cff'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
