"""init

Revision ID: 39ec22bbadd4
Revises: f2fe3744995e
Create Date: 2023-09-11 23:04:08.845536

"""

# revision identifiers, used by Alembic.
revision = '39ec22bbadd4'
down_revision = 'f2fe3744995e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
