"""init

Revision ID: 3bf28a21cd4b
Revises: 390c5583f6d7
Create Date: 2023-09-06 09:55:33.629731

"""

# revision identifiers, used by Alembic.
revision = '3bf28a21cd4b'
down_revision = '390c5583f6d7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
