"""init

Revision ID: 3c73f03460bb
Revises: 75adea42bf20
Create Date: 2023-09-11 18:10:06.442288

"""

# revision identifiers, used by Alembic.
revision = '3c73f03460bb'
down_revision = '75adea42bf20'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

