"""init

Revision ID: 3d7aa62cb942
Revises: 39ec22bbadd4
Create Date: 2023-09-11 23:06:28.384832

"""

# revision identifiers, used by Alembic.
revision = '3d7aa62cb942'
down_revision = '39ec22bbadd4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
