"""init

Revision ID: 475ef80885d0
Revises: c489b796429f
Create Date: 2023-09-10 10:24:30.890994

"""

# revision identifiers, used by Alembic.
revision = '475ef80885d0'
down_revision = 'c489b796429f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
