"""init

Revision ID: 498684a5b262
Revises: 6fe152c694f4
Create Date: 2023-09-06 09:23:47.301115

"""

# revision identifiers, used by Alembic.
revision = '498684a5b262'
down_revision = '6fe152c694f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
