"""init

Revision ID: 4b977fc9b56b
Revises: e7ea9ec8984d
Create Date: 2023-09-10 09:43:49.639405

"""

# revision identifiers, used by Alembic.
revision = '4b977fc9b56b'
down_revision = 'e7ea9ec8984d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
