"""init

Revision ID: 51552872ec8b
Revises: ea5642224f80
Create Date: 2023-09-11 18:17:43.646048

"""

# revision identifiers, used by Alembic.
revision = '51552872ec8b'
down_revision = 'ea5642224f80'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
