"""init

Revision ID: 53fba5fdad53
Revises: d9a76d2927b5
Create Date: 2023-09-11 22:39:33.231536

"""

# revision identifiers, used by Alembic.
revision = '53fba5fdad53'
down_revision = 'd9a76d2927b5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
