"""init

Revision ID: 56242c2e5b2f
Revises: ad412cc991e2
Create Date: 2023-09-06 08:44:23.054691

"""

# revision identifiers, used by Alembic.
revision = '56242c2e5b2f'
down_revision = 'ad412cc991e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
