"""init

Revision ID: 6aef992f0d6f
Revises: 71dc47516bf8
Create Date: 2023-09-11 23:07:29.019364

"""

# revision identifiers, used by Alembic.
revision = '6aef992f0d6f'
down_revision = '71dc47516bf8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
