"""init

Revision ID: 6fe152c694f4
Revises: 76418d740378
Create Date: 2023-09-06 09:02:18.759029

"""

# revision identifiers, used by Alembic.
revision = '6fe152c694f4'
down_revision = '76418d740378'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
