"""init

Revision ID: 71dc47516bf8
Revises: 3d7aa62cb942
Create Date: 2023-09-11 23:07:06.860976

"""

# revision identifiers, used by Alembic.
revision = '71dc47516bf8'
down_revision = '3d7aa62cb942'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
