"""init

Revision ID: 73c5362801e6
Revises: d0c46739f69c
Create Date: 2023-09-11 19:24:25.898055

"""

# revision identifiers, used by Alembic.
revision = '73c5362801e6'
down_revision = 'd0c46739f69c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
