"""init

Revision ID: 75adea42bf20
Revises: 020c6d183ad1
Create Date: 2023-09-11 17:21:07.864492

"""

# revision identifiers, used by Alembic.
revision = '75adea42bf20'
down_revision = '020c6d183ad1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
