"""init

Revision ID: 76418d740378
Revises: d10bc6b42472
Create Date: 2023-09-06 09:01:40.003839

"""

# revision identifiers, used by Alembic.
revision = '76418d740378'
down_revision = 'd10bc6b42472'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
