"""init

Revision ID: 7f5ca6146bf5
Revises: badd09fa9606
Create Date: 2023-09-06 10:05:41.476836

"""

# revision identifiers, used by Alembic.
revision = '7f5ca6146bf5'
down_revision = 'badd09fa9606'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
