"""init

Revision ID: 8b0cad7d17b3
Revises: 916d6c5bf7b0
Create Date: 2023-09-06 09:58:55.490493

"""

# revision identifiers, used by Alembic.
revision = '8b0cad7d17b3'
down_revision = '916d6c5bf7b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
