"""init

Revision ID: 8d954cef5c5d
Revises: 993528f3768e
Create Date: 2023-09-11 23:01:06.182967

"""

# revision identifiers, used by Alembic.
revision = '8d954cef5c5d'
down_revision = '993528f3768e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
