"""init

Revision ID: 916d6c5bf7b0
Revises: 3bf28a21cd4b
Create Date: 2023-09-06 09:58:42.798921

"""

# revision identifiers, used by Alembic.
revision = '916d6c5bf7b0'
down_revision = '3bf28a21cd4b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
