"""init

Revision ID: 95cab37b30fa
Revises: fcb52dca5188
Create Date: 2023-09-10 10:15:36.630511

"""

# revision identifiers, used by Alembic.
revision = '95cab37b30fa'
down_revision = 'fcb52dca5188'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
