"""init

Revision ID: 984bfcafb392
Revises: 1c79a57c2247
Create Date: 2023-09-11 22:26:37.608845

"""

# revision identifiers, used by Alembic.
revision = '984bfcafb392'
down_revision = '1c79a57c2247'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
