"""init

Revision ID: 993528f3768e
Revises: 53fba5fdad53
Create Date: 2023-09-11 22:45:06.373642

"""

# revision identifiers, used by Alembic.
revision = '993528f3768e'
down_revision = '53fba5fdad53'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
