"""init

Revision ID: 994bf30fc039
Revises: e3105b2fb24a
Create Date: 2023-09-10 09:15:53.319955

"""

# revision identifiers, used by Alembic.
revision = '994bf30fc039'
down_revision = 'e3105b2fb24a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
