"""init

Revision ID: a328ce42ad1f
Revises: 1733abbfd661
Create Date: 2023-09-11 19:19:26.767527

"""

# revision identifiers, used by Alembic.
revision = 'a328ce42ad1f'
down_revision = '1733abbfd661'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
