"""init

Revision ID: a9e52fda5e93
Revises: 94906b42fedf
Create Date: 2023-09-11 19:12:26.868457

"""

# revision identifiers, used by Alembic.
revision = 'a9e52fda5e93'
down_revision = '94906b42fedf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
