"""init

Revision ID: ad18d73f9a45
Revises: d882c68d2318
Create Date: 2023-09-11 19:16:23.339760

"""

# revision identifiers, used by Alembic.
revision = 'ad18d73f9a45'
down_revision = 'd882c68d2318'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
