"""init

Revision ID: ae8c6a718f04
Revises: f7761efdc987
Create Date: 2023-09-10 09:41:27.851579

"""

# revision identifiers, used by Alembic.
revision = 'ae8c6a718f04'
down_revision = 'f7761efdc987'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
