"""init

Revision ID: b7313ee54cff
Revises: 498684a5b262
Create Date: 2023-09-06 09:28:05.277707

"""

# revision identifiers, used by Alembic.
revision = 'b7313ee54cff'
down_revision = '498684a5b262'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
