"""init

Revision ID: badd09fa9606
Revises: 8b0cad7d17b3
Create Date: 2023-09-06 10:01:45.221729

"""

# revision identifiers, used by Alembic.
revision = 'badd09fa9606'
down_revision = '8b0cad7d17b3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
