"""init

Revision ID: bfd632dce7d6
Revises: dc994b6ced67
Create Date: 2023-09-10 10:13:27.379579

"""

# revision identifiers, used by Alembic.
revision = 'bfd632dce7d6'
down_revision = 'dc994b6ced67'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
