"""init

Revision ID: c08f3d7cc2ef
Revises: 38b6588e6618
Create Date: 2023-09-06 09:00:52.049327

"""

# revision identifiers, used by Alembic.
revision = 'c08f3d7cc2ef'
down_revision = '38b6588e6618'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
