"""init

Revision ID: c2212ad9705c
Revises: 73c5362801e6
Create Date: 2023-09-11 19:37:55.587826

"""

# revision identifiers, used by Alembic.
revision = 'c2212ad9705c'
down_revision = '73c5362801e6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
