"""init

Revision ID: c489b796429f
Revises: d7c20d9e945a
Create Date: 2023-09-10 10:19:58.332656

"""

# revision identifiers, used by Alembic.
revision = 'c489b796429f'
down_revision = 'd7c20d9e945a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
