"""init

Revision ID: c4b1361b6dd0
Revises: 6aef992f0d6f
Create Date: 2023-09-11 23:08:10.675692

"""

# revision identifiers, used by Alembic.
revision = 'c4b1361b6dd0'
down_revision = '6aef992f0d6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
