"""init

Revision ID: d0c46739f69c
Revises: a328ce42ad1f
Create Date: 2023-09-11 19:23:05.370699

"""

# revision identifiers, used by Alembic.
revision = 'd0c46739f69c'
down_revision = 'a328ce42ad1f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
