"""init

Revision ID: d10bc6b42472
Revises: c08f3d7cc2ef
Create Date: 2023-09-06 09:01:09.532805

"""

# revision identifiers, used by Alembic.
revision = 'd10bc6b42472'
down_revision = 'c08f3d7cc2ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
