"""init

Revision ID: d5c6c1541f5e
Revises: 475ef80885d0
Create Date: 2023-09-10 10:40:28.044528

"""

# revision identifiers, used by Alembic.
revision = 'd5c6c1541f5e'
down_revision = '475ef80885d0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
