"""init

Revision ID: d67fdcad6fe9
Revises: c4b1361b6dd0
Create Date: 2023-09-11 23:08:19.106148

"""

# revision identifiers, used by Alembic.
revision = 'd67fdcad6fe9'
down_revision = 'c4b1361b6dd0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
