"""init

Revision ID: d7c20d9e945a
Revises: 95cab37b30fa
Create Date: 2023-09-10 10:17:31.515430

"""

# revision identifiers, used by Alembic.
revision = 'd7c20d9e945a'
down_revision = '95cab37b30fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
