"""init

Revision ID: d882c68d2318
Revises: a9e52fda5e93
Create Date: 2023-09-11 19:13:32.382726

"""

# revision identifiers, used by Alembic.
revision = 'd882c68d2318'
down_revision = 'a9e52fda5e93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
