"""init

Revision ID: d9a76d2927b5
Revises: f9957cac000d
Create Date: 2023-09-11 22:34:31.229195

"""

# revision identifiers, used by Alembic.
revision = 'd9a76d2927b5'
down_revision = 'f9957cac000d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
