"""init

Revision ID: dc994b6ced67
Revises: f77e54245a63
Create Date: 2023-09-10 10:10:56.647049

"""

# revision identifiers, used by Alembic.
revision = 'dc994b6ced67'
down_revision = 'f77e54245a63'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
