"""init

Revision ID: ddea345a6dba
Revises: 1693fd838c7d
Create Date: 2023-09-10 09:52:42.768270

"""

# revision identifiers, used by Alembic.
revision = 'ddea345a6dba'
down_revision = '1693fd838c7d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
