"""init

Revision ID: de001562e017
Revises: 8d954cef5c5d
Create Date: 2023-09-11 23:03:05.651420

"""

# revision identifiers, used by Alembic.
revision = 'de001562e017'
down_revision = '8d954cef5c5d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
