"""init

Revision ID: e3105b2fb24a
Revises: f4875a231d3b
Create Date: 2023-09-06 10:27:08.093441

"""

# revision identifiers, used by Alembic.
revision = 'e3105b2fb24a'
down_revision = 'f4875a231d3b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
