"""init

Revision ID: e7ea9ec8984d
Revises: 1494aa305d9a
Create Date: 2023-09-10 09:43:12.418174

"""

# revision identifiers, used by Alembic.
revision = 'e7ea9ec8984d'
down_revision = '1494aa305d9a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
