"""init

Revision ID: ea5642224f80
Revises: 3c73f03460bb
Create Date: 2023-09-11 18:15:29.542467

"""

# revision identifiers, used by Alembic.
revision = 'ea5642224f80'
down_revision = '3c73f03460bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
