"""init

Revision ID: f0cd07a33e45
Revises: 994bf30fc039
Create Date: 2023-09-10 09:18:15.640585

"""

# revision identifiers, used by Alembic.
revision = 'f0cd07a33e45'
down_revision = '994bf30fc039'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
