"""init

Revision ID: f23ee48fd220
Revises: 2c94aa7d77bb
Create Date: 2023-09-11 22:24:13.918910

"""

# revision identifiers, used by Alembic.
revision = 'f23ee48fd220'
down_revision = '2c94aa7d77bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
