"""init

Revision ID: f2fe3744995e
Revises: f3503448ecdc
Create Date: 2023-09-11 23:04:04.256190

"""

# revision identifiers, used by Alembic.
revision = 'f2fe3744995e'
down_revision = 'f3503448ecdc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
