"""init

Revision ID: f3503448ecdc
Revises: de001562e017
Create Date: 2023-09-11 23:03:10.848231

"""

# revision identifiers, used by Alembic.
revision = 'f3503448ecdc'
down_revision = 'de001562e017'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
