"""init

Revision ID: f4875a231d3b
Revises: 7f5ca6146bf5
Create Date: 2023-09-06 10:08:17.168168

"""

# revision identifiers, used by Alembic.
revision = 'f4875a231d3b'
down_revision = '7f5ca6146bf5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
