"""init

Revision ID: f7761efdc987
Revises: f0cd07a33e45
Create Date: 2023-09-10 09:39:43.225397

"""

# revision identifiers, used by Alembic.
revision = 'f7761efdc987'
down_revision = 'f0cd07a33e45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
