"""init

Revision ID: f77e54245a63
Revises: 25fe01d31c06
Create Date: 2023-09-10 10:09:56.911270

"""

# revision identifiers, used by Alembic.
revision = 'f77e54245a63'
down_revision = '25fe01d31c06'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
