"""init

Revision ID: f9957cac000d
Revises: 984bfcafb392
Create Date: 2023-09-11 22:28:20.807045

"""

# revision identifiers, used by Alembic.
revision = 'f9957cac000d'
down_revision = '984bfcafb392'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
