"""init

Revision ID: fcb52dca5188
Revises: bfd632dce7d6
Create Date: 2023-09-10 10:14:33.779665

"""

# revision identifiers, used by Alembic.
revision = 'fcb52dca5188'
down_revision = 'bfd632dce7d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
