"""init

Revision ID: fd8aaf8f7e94
Revises: 16192d0c8c5f
Create Date: 2023-09-11 19:53:09.383485

"""

# revision identifiers, used by Alembic.
revision = 'fd8aaf8f7e94'
down_revision = '16192d0c8c5f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
