"""init

Revision ID: fe7779a44444
Revises: 15cacf37e03a
Create Date: 2023-09-10 09:58:14.906542

"""

# revision identifiers, used by Alembic.
revision = 'fe7779a44444'
down_revision = '15cacf37e03a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
